import switchImg from '../../assets/switch.png'

const 紫色 = '#873bf4'
const 绿色 = 'green'
const 红色 = 'red'
const 白色 = '#fff'
const 电信光纤线路40G = {
  style: {
    lineWidth: 2,
    lineDash: [2, 2],
    stroke: 红色,
  },
}
const 联通光纤线路40G = {
  style: {
    lineWidth: 2,
    stroke: 绿色,
  },
}

const 联通光纤线路10G = {
  style: {
    lineWidth: 1,
    stroke: 绿色,
  },
}

const 广电光纤线路10G = {
  style: {
    lineWidth: 1,
    stroke: 紫色,
  },
}

export const legendData = {
  edges: [
    {
      type: 'line',
      id: '电信光纤线路40G',
      label: '40G电信光纤线路',
      style: {
        width: 50,
        ...电信光纤线路40G.style,
      },
      labelCfg: {
        style: { fill: 白色 },
      },
    },
    {
      type: 'line',
      id: '联通光纤线路40G',
      label: '40G联通光纤线路',
      style: {
        width: 50,
        ...联通光纤线路40G.style,
      },
      labelCfg: {
        style: { fill: 白色 },
      },
    },
    {
      type: 'line',
      id: '联通光纤线路10G',
      label: '10G联通光纤线路',
      style: {
        width: 50,
        ...联通光纤线路10G.style,
      },
      labelCfg: {
        style: { fill: 白色 },
      },
    },
    {
      type: 'line',
      id: '广电光纤线路10G',
      label: '10G广电光纤线路',
      style: {
        width: 50,
        ...广电光纤线路10G.style,
      },
      labelCfg: {
        style: { fill: 白色 },
      },
    },
  ],
}
export const data = {
  // 点集
  nodes: [
    {
      id: 'DC1node',
      label: 'Combos1',
      comboId: 'Combos1',
      x: 400,
      y: 100,
    },
    {
      id: 'DC2node',
      label: 'Combos2',
      comboId: 'Combos2',
      x: 800,
      y: 100,
    },
    {
      id: '星港学校本部',
      label: '星港学校本部',
      type: 'image',
      x: 50,
      y: 300,
    },
    {
      id: '星港学校东港分校',
      label: '星港学校东港分校',
      type: 'image',
      x: 50,
      y: 350,
    },
    {
      id: '星港学校苏安分校',
      label: '星港学校苏安分校',
      type: 'image',
      x: 50,
      y: 400,
    },
    {
      id: '星洲小学',
      label: '星洲小学',
      type: 'image',
      x: 150,
      y: 300,
    },
    {
      id: '星海小学',
      label: '星海小学',
      type: 'image',
      x: 150,
      y: 350,
    },
    {
      id: '星海中学',
      label: '星海中学',
      type: 'image',
      x: 150,
      y: 400,
    },
    {
      id: '园区一中',
      label: '园区一中',
      type: 'image',
      x: 150,
      y: 450,
    },
    {
      id: '胜浦实验中学',
      label: '胜浦实验中学',
      type: 'image',
      x: 150,
      y: 500,
    },
    {
      id: '胜浦实验小学',
      label: '胜浦实验小学',
      type: 'image',
      x: 150,
      y: 550,
    },
    {
      id: '翰林小学',
      label: '翰林小学',
      type: 'image',
      x: 250,
      y: 400,
    },
    {
      id: '西交大附属高中',
      label: '西交大附属高中',
      type: 'image',
      x: 350,
      y: 400,
    },
    {
      id: '西交大附属初中',
      label: '西交大附属初中',
      type: 'image',
      x: 450,
      y: 400,
    },
    {
      id: '星湾学校',
      label: '星湾学校',
      type: 'image',
      x: 550,
      y: 400,
    },
    {
      id: '星湾学校西区',
      label: '星湾学校西区',
      type: 'image',
      x: 600,
      y: 465,
    },
    {
      id: '新城花园小学',
      label: '新城花园小学',
      type: 'image',
      x: 650,
      y: 400,
    },
    {
      id: '金鸡湖学校',
      label: '金鸡湖学校',
      type: 'image',
      x: 750,
      y: 400,
    },
    {
      id: '青剑湖学校',
      label: '青剑湖学校',
      type: 'image',
      x: 850,
      y: 400,
    },
    {
      id: '唯亭实验小学',
      label: '唯亭实验小学',
      type: 'image',
      x: 950,
      y: 400,
    },
    {
      id: '车坊小学',
      label: '车坊小学',
      type: 'image',
      x: 1050,
      y: 400,
    },
    {
      id: '娄葑实验小学',
      label: '娄葑实验小学',
      type: 'image',
      x: 950,
      y: 300,
    },
    {
      id: '跨塘实验小学',
      label: '跨塘实验小学',
      type: 'image',
      x: 1050,
      y: 300,
    },
    {
      id: '景城学校',
      label: '景城学校',
      type: 'image',
      x: 1150,
      y: 300,
    },
    {
      id: '星洋学校',
      label: '星洋学校',
      type: 'image',
      x: 1150,
      y: 350,
    },
    {
      id: '文萃小学',
      label: '文萃小学',
      type: 'image',
      x: 1150,
      y: 400,
    },
    {
      id: '园区二实小',
      label: '园区二实小',
      type: 'image',
      x: 1150,
      y: 450,
    },
    {
      id: '园区三实小',
      label: '园区三实小',
      type: 'image',
      x: 1150,
      y: 500,
    },
    {
      id: '星浦学校',
      label: '星浦学校',
      type: 'image',
      x: 1150,
      y: 550,
    },
    {
      id: '星澜学校',
      label: '星澜学校',
      type: 'image',
      x: 1150,
      y: 600,
    },
    {
      id: '斜塘学校',
      label: '斜塘学校',
      type: 'image',
      x: 1250,
      y: 300,
    },
    {
      id: '东延路实验学校',
      label: '东延路实验学校',
      type: 'image',
      x: 1250,
      y: 350,
    },
    {
      id: '独墅湖学校',
      label: '独墅湖学校',
      type: 'image',
      x: 1250,
      y: 400,
    },
    {
      id: '白榆路机房',
      label: '白榆路机房',
      type: 'image',
      x: 250,
      y: 500,
    },
    {
      id: '教师发展中心',
      label: '教师发展中心',
      type: 'image',
      x: 350,
      y: 500,
    },
    {
      id: '娄葑学校',
      label: '娄葑学校',
      type: 'image',
      x: 450,
      y: 500,
    },
    {
      id: '学生公寓B区机房',
      label: '学生公寓B区机房',
      type: 'image',
      x: 550,
      y: 500,
    },
    {
      id: '方洲小学',
      label: '方洲小学',
      type: 'image',
      x: 650,
      y: 500,
    },
    {
      id: '星华街机房',
      label: '星华街机房',
      type: 'image',
      x: 750,
      y: 500,
    },
    {
      id: '莲花学校',
      label: '莲花学校',
      type: 'image',
      x: 850,
      y: 500,
    },
    {
      id: '唯亭大道机房',
      label: '唯亭大道机房',
      type: 'image',
      x: 950,
      y: 500,
    },
    {
      id: '星汇学校',
      label: '星汇学校',
      type: 'image',
      x: 1050,
      y: 500,
    },

    {
      id: '新城花园幼儿园',
      label: '新城花园幼儿园',
      type: 'image',
      img: switchImg,
      x: 150,
      y: 600,
    },
    {
      id: '新加花园幼儿园',
      label: '新加花园幼儿园',
      type: 'image',
      img: switchImg,
      x: 250,
      y: 600,
    },
    {
      id: '新馨花园幼儿园',
      label: '新馨花园幼儿园',
      type: 'image',
      img: switchImg,
      x: 350,
      y: 600,
    },
    {
      id: '天域幼儿园',
      label: '天域幼儿园',
      type: 'image',
      img: switchImg,
      x: 430,
      y: 600,
    },
    {
      id: '华林幼儿园',
      label: '华林幼儿园',
      type: 'image',
      img: switchImg,
      x: 510,
      y: 600,
    },
    {
      id: '翰林幼儿园',
      label: '翰林幼儿园',
      type: 'image',
      img: switchImg,
      x: 580,
      y: 600,
    },
    {
      id: '景城幼儿园',
      label: '景城幼儿园',
      type: 'image',
      img: switchImg,
      x: 650,
      y: 600,
    },
    {
      id: '新洲幼儿园',
      label: '新洲幼儿园',
      type: 'image',
      img: switchImg,
      x: 720,
      y: 600,
    },
    {
      id: '尚城幼儿园',
      label: '尚城幼儿园',
      type: 'image',
      img: switchImg,
      x: 790,
      y: 600,
    },
    {
      id: '星慧幼儿园',
      label: '星慧幼儿园',
      type: 'image',
      img: switchImg,
      x: 860,
      y: 600,
    },
    {
      id: '钟园幼儿园',
      label: '钟园幼儿园',
      type: 'image',
      img: switchImg,
      x: 930,
      y: 600,
    },
    {
      id: '翡翠幼儿园',
      label: '翡翠幼儿园',
      type: 'image',
      img: switchImg,
      x: 1000,
      y: 600,
    },
  ],
  // 边集
  edges: [
    {
      source: 'DC1node',
      target: '星洲小学',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '白榆路机房',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '白榆路机房',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '西交大附属初中',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '学生公寓B区机房',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '学生公寓B区机房',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '方洲小学',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '星华街机房',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '星华街机房',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '星湾学校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '星湾学校西区',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '星湾学校西区',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '新城花园小学',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '金鸡湖学校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '青剑湖学校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '莲花学校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '车坊小学',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '唯亭大道机房',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '唯亭大道机房',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '星汇学校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '星汇学校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '园区三实小',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '园区三实小',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '星浦学校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '星浦学校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '星澜学校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '星澜学校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '星港学校本部',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '星港学校本部',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '星港学校东港分校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '星港学校东港分校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '星港学校苏安分校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '星港学校苏安分校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '斜塘学校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '斜塘学校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '东延路实验学校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '东延路实验学校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '独墅湖学校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '独墅湖学校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '景城学校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '星洋学校',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '文萃小学',
      legendType: '联通光纤线路40G',
      ...联通光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '星洲小学',
      legendType: '电信光纤线路40G',
      ...电信光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '西交大附属初中',
      legendType: '电信光纤线路40G',
      ...电信光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '星湾学校',
      legendType: '电信光纤线路40G',
      ...电信光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '新城花园小学',
      legendType: '电信光纤线路40G',
      ...电信光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '方洲小学',
      legendType: '电信光纤线路40G',
      ...电信光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '西交大附属初中',
      legendType: '电信光纤线路40G',
      ...电信光纤线路40G,
    },
    {
      source: 'DC1node',
      target: '金鸡湖学校',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC2node',
      target: '青剑湖学校',
      legendType: '电信光纤线路40G',
      ...电信光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '莲花学校',
      legendType: '电信光纤线路40G',
      ...电信光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '车坊小学',
      legendType: '电信光纤线路40G',
      ...电信光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '景城学校',
      legendType: '电信光纤线路40G',
      ...电信光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '星洋学校',
      legendType: '电信光纤线路40G',
      ...电信光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '文萃小学',
      legendType: '电信光纤线路40G',
      ...电信光纤线路40G,
    },
    {
      source: 'DC2node',
      target: '星海小学',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC1node',
      target: '星海中学',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC2node',
      target: '星海中学',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC1node',
      target: '园区一中',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC2node',
      target: '园区一中',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC1node',
      target: '胜浦实验中学',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC2node',
      target: '胜浦实验中学',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC1node',
      target: '胜浦实验小学',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC2node',
      target: '胜浦实验小学',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC1node',
      target: '翰林小学',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC2node',
      target: '翰林小学',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC1node',
      target: '西交大附属高中',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC2node',
      target: '西交大附属高中',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC1node',
      target: '翰林小学',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC2node',
      target: '翰林小学',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC1node',
      target: '教师发展中心',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC2node',
      target: '教师发展中心',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC1node',
      target: '娄葑学校',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC2node',
      target: '娄葑学校',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC1node',
      target: '唯亭实验小学',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC2node',
      target: '唯亭实验小学',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC1node',
      target: '娄葑实验小学',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC2node',
      target: '娄葑实验小学',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC1node',
      target: '跨塘实验小学',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC2node',
      target: '跨塘实验小学',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC1node',
      target: '园区二实小',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: 'DC2node',
      target: '园区二实小',
      legendType: '广电光纤线路10G',
      ...广电光纤线路10G,
    },
    {
      source: '白榆路机房',
      target: '新城花园幼儿园',
      legendType: '联通光纤线路10G',
      ...联通光纤线路10G,
    },
    {
      source: '白榆路机房',
      target: '新加花园幼儿园',
      legendType: '联通光纤线路10G',
      ...联通光纤线路10G,
    },
    {
      source: '白榆路机房',
      target: '新馨花园幼儿园',
      legendType: '联通光纤线路10G',
      ...联通光纤线路10G,
    },
    {
      source: '白榆路机房',
      target: '天域幼儿园',
      legendType: '联通光纤线路10G',
      ...联通光纤线路10G,
    },
    {
      source: '学生公寓B区机房',
      target: '华林幼儿园',
      legendType: '联通光纤线路10G',
      ...联通光纤线路10G,
    },
    {
      source: '学生公寓B区机房',
      target: '翰林幼儿园',
      legendType: '联通光纤线路10G',
      ...联通光纤线路10G,
    },
    {
      source: '星华街机房',
      target: '景城幼儿园',
      legendType: '联通光纤线路10G',
      ...联通光纤线路10G,
    },
    {
      source: '星华街机房',
      target: '新洲幼儿园',
      legendType: '联通光纤线路10G',
      ...联通光纤线路10G,
    },
    {
      source: '星华街机房',
      target: '尚城幼儿园',
      legendType: '联通光纤线路10G',
      ...联通光纤线路10G,
    },
    {
      source: '星华街机房',
      target: '星慧幼儿园',
      legendType: '联通光纤线路10G',
      ...联通光纤线路10G,
    },
    {
      source: '星华街机房',
      target: '钟园幼儿园',
      legendType: '联通光纤线路10G',
      ...联通光纤线路10G,
    },
    {
      source: '唯亭大道机房',
      target: '翡翠幼儿园',
      legendType: '联通光纤线路10G',
      ...联通光纤线路10G,
    },
  ],
  combos: [
    {
      id: 'Combos1',
      label: 'Combos1',
    },
    {
      id: 'Combos2',
      label: 'Combos2',
    },
  ],
}
