import switchImg from '../../assets/switch.png'
import combosBg from '../../assets/combos.png'

const 供应商3光纤颜色 = '#4fcff7'
const 供应商1光纤40G颜色 = '#b1a220'
const 供应商1光纤10G颜色 = '#6df2a8'
const 供应商2光纤颜色 = '#894bf5'
const 路由器节点样式 = {
  labelCfg: {
    style: {
      fill: '#8bd5d9',
    },
  },
}
const 供应商2光纤线路40G = {
  style: {
    stroke: 供应商2光纤颜色,
  },
}
const 供应商1光纤线路40G = {
  style: {
    stroke: 供应商1光纤40G颜色,
  },
}

const 供应商1光纤线路10G = {
  style: {
    stroke: 供应商1光纤10G颜色,
  },
}

const 供应商3光纤线路10G = {
  style: {
    stroke: 供应商3光纤颜色,
  },
}
const legendEdgesStyle = {
  cursor: 'grab',
  lineWidth: 3,
  width: 70,
}
const legendEdgesLabelCfg = {
  style: { fill: '#fff', cursor: 'grab' },
}
export const legendData = {
  edges: [
    {
      type: 'line',
      id: '供应商2光纤线路40G',
      label: '40G供应商2光纤线路',
      style: {
        ...供应商2光纤线路40G.style,
        ...legendEdgesStyle,
      },
      labelCfg: legendEdgesLabelCfg,
    },
    {
      type: 'line',
      id: '供应商1光纤线路40G',
      label: '40G供应商1光纤线路',
      style: {
        ...供应商1光纤线路40G.style,
        ...legendEdgesStyle,
      },
      labelCfg: legendEdgesLabelCfg,
    },
    {
      type: 'line',
      id: '供应商1光纤线路10G',
      label: '10G供应商1光纤线路',
      style: {
        ...供应商1光纤线路10G.style,
        ...legendEdgesStyle,
      },
      labelCfg: legendEdgesLabelCfg,
    },
    {
      type: 'line',
      id: '供应商3光纤线路10G',
      label: '10G供应商3光纤线路',
      style: {
        ...供应商3光纤线路10G.style,
        ...legendEdgesStyle,
      },
      labelCfg: legendEdgesLabelCfg,
    },
  ],
}
export const data = {
  // 点集
  nodes: [
    {
      id: 'DC1大数据管理中心',
      label: 'DC1大数据管理中心',
      x: 400,
      y: 50,
      img: combosBg,
      size: [250, 130],
      labelCfg: {
        position: 'top',
        offset: -21,
        style: {
          fill: '#4fcff7',
        },
      },
    },
    {
      id: 'DC2大数据管理中心',
      label: 'DC2大数据管理中心',
      x: 800,
      y: 50,
      img: combosBg,
      size: [250, 130],
      labelCfg: {
        position: 'top',
        offset: -21,
        style: {
          fill: '#4fcff7',
        },
      },
    },
    {
      id: 'DC1node',
      label: 'SDN H3C S10508X-V',
      x: 400,
      y: 50,
    },
    {
      id: 'DC2node',
      label: 'SDN H3C S10508X-V',
      x: 800,
      y: 50,
    },
    {
      id: '西交大附属高中',
      label: '西交大附属高中',
      x: 40,
      y: 220,
    },
    {
      id: '教师发展中区',
      label: '教师发展中区',
      x: 40,
      y: 300,
    },
    {
      id: '娄葑地区',
      label: '娄葑地区',
      x: 40,
      y: 380,
    },
    {
      id: '娄葑实验小地区',
      label: '娄葑实验小地区',
      x: 40,
      y: 460,
    },
    {
      id: '园区二实小',
      label: '园区二实小',
      x: 40,
      y: 540,
    },
    {
      id: '跨塘实验小地区',
      label: '跨塘实验小地区',
      x: 40,
      y: 620,
    },
    {
      id: '星海小地区',
      label: '星海小地区',
      x: 130,
      y: 220,
    },
    {
      id: '园区一中',
      label: '园区一中',
      x: 130,
      y: 300,
    },
    {
      id: '胜浦实验中地区',
      label: '胜浦实验中地区',
      x: 130,
      y: 380,
    },
    {
      id: '胜浦实验小地区',
      label: '胜浦实验小地区',
      x: 130,
      y: 460,
    },

    {
      id: '翰林小地区',
      label: '翰林小地区',
      x: 130,
      y: 540,
    },
    {
      id: '唯亭实验小地区',
      label: '唯亭实验小地区',
      x: 130,
      y: 620,
    },
    {
      id: '金鸡湖地区',
      label: '金鸡湖地区',
      x: 280,
      y: 380,
    },
    {
      id: '星港地区东港分区',
      label: '星港地区东港分区',
      x: 380,
      y: 380,
    },
    {
      id: '星港地区苏安分区',
      label: '星港地区苏安分区',
      x: 480,
      y: 380,
    },
    {
      id: '星浦地区',
      label: '星浦地区',
      x: 580,
      y: 380,
    },
    {
      id: '星澜地区',
      label: '星澜地区',
      x: 680,
      y: 380,
    },
    {
      id: '斜塘地区',
      label: '斜塘地区',
      x: 780,
      y: 380,
    },
    {
      id: '东延路实验地区',
      label: '东延路实验地区',
      x: 880,
      y: 380,
    },
    {
      id: '独墅湖地区',
      label: '独墅湖地区',
      x: 980,
      y: 380,
    },

    {
      id: '星海中地区',
      label: '星海中地区',
      x: 230,
      y: 460,
    },
    {
      id: '学生公寓B区机房',
      label: '学生公寓B区机房',
      x: 330,
      y: 460,
    },
    {
      id: '星港地区本部',
      label: '星港地区本部',
      x: 430,
      y: 460,
    },
    {
      id: '白榆路机房',
      label: '白榆路机房',
      x: 530,
      y: 460,
    },
    {
      id: '园区三实小',
      label: '园区三实小',
      x: 630,
      y: 460,
    },
    {
      id: '星湾地区西区',
      label: '星湾地区西区',
      x: 730,
      y: 460,
    },
    {
      id: '星华街机房',
      label: '星华街机房',
      x: 830,
      y: 460,
    },
    {
      id: '星汇地区',
      label: '星汇地区',
      x: 930,
      y: 460,
    },
    {
      id: '唯亭大道机房',
      label: '唯亭大道机房',
      x: 1030,
      y: 460,
    },
    {
      id: '车坊小地区',
      label: '车坊小地区',
      x: 1100,
      y: 220,
    },

    {
      id: '景城地区',
      label: '景城地区',
      x: 1100,
      y: 300,
    },
    {
      id: '星洋地区',
      label: '星洋地区',
      x: 1100,
      y: 380,
    },
    {
      id: '文萃小地区',
      label: '文萃小地区',
      x: 1100,
      y: 460,
    },

    {
      id: '西交大附属初中',
      label: '西交大附属初中',
      x: 1100,
      y: 540,
    },

    {
      id: '莲花地区',
      label: '莲花地区',
      x: 1200,
      y: 220,
    },
    {
      id: '方洲小地区',
      label: '方洲小地区',
      x: 1200,
      y: 300,
    },

    {
      id: '星湾地区',
      label: '星湾地区',
      x: 1200,
      y: 380,
    },
    {
      id: '新城花园小地区',
      label: '新城花园小地区',
      x: 1200,
      y: 460,
    },
    {
      id: '青剑湖地区',
      label: '青剑湖地区',
      x: 1200,
      y: 540,
    },

    {
      id: '星洲小地区',
      label: '星洲小地区',
      x: 1200,
      y: 620,
    },

    {
      id: '新馨花园建筑物',
      label: '新馨花园建筑物',
      type: 'image',
      img: switchImg,
      x: 370,
      y: 620,
      ...路由器节点样式,
    },
    {
      id: '天域建筑物',
      label: '天域建筑物',
      type: 'image',
      img: switchImg,
      x: 450,
      y: 620,
      ...路由器节点样式,
    },
    {
      id: '新城花园建筑物',
      label: '新城花园建筑物',
      type: 'image',
      img: switchImg,
      x: 530,
      y: 620,
      ...路由器节点样式,
    },

    {
      id: '新加花园建筑物',
      label: '新加花园建筑物',
      type: 'image',
      img: switchImg,
      x: 620,
      y: 620,
      ...路由器节点样式,
    },
    {
      id: '华林建筑物',
      label: '华林建筑物',
      type: 'image',
      img: switchImg,
      x: 220,
      y: 620,
      ...路由器节点样式,
    },
    {
      id: '翰林建筑物',
      label: '翰林建筑物',
      type: 'image',
      img: switchImg,
      x: 290,
      y: 620,
      ...路由器节点样式,
    },
    {
      id: '景城建筑物',
      label: '景城建筑物',
      type: 'image',
      img: switchImg,
      x: 700,
      y: 620,
      ...路由器节点样式,
    },
    {
      id: '新洲建筑物',
      label: '新洲建筑物',
      type: 'image',
      img: switchImg,
      x: 770,
      y: 620,
      ...路由器节点样式,
    },
    {
      id: '尚城建筑物',
      label: '尚城建筑物',
      type: 'image',
      img: switchImg,
      x: 840,
      y: 620,
      ...路由器节点样式,
    },
    {
      id: '星慧建筑物',
      label: '星慧建筑物',
      type: 'image',
      img: switchImg,
      x: 910,
      y: 620,
      ...路由器节点样式,
    },
    {
      id: '钟园建筑物',
      label: '钟园建筑物',
      type: 'image',
      img: switchImg,
      x: 980,
      y: 620,
      ...路由器节点样式,
    },
    {
      id: '翡翠建筑物',
      label: '翡翠建筑物',
      type: 'image',
      img: switchImg,
      x: 1050,
      y: 620,
      ...路由器节点样式,
    },
  ],
  // 边集
  edges: [
    {
      source: 'DC1大数据管理中心',
      target: '星洲小地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '白榆路机房',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '白榆路机房',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '西交大附属初中',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '学生公寓B区机房',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '学生公寓B区机房',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '方洲小地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '星华街机房',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '星华街机房',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '星湾地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '星湾地区西区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '星湾地区西区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '新城花园小地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '金鸡湖地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '青剑湖地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '莲花地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '车坊小地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '唯亭大道机房',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '唯亭大道机房',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '星汇地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '星汇地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '园区三实小',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '园区三实小',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '星浦地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '星浦地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '星澜地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '星澜地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '星港地区本部',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '星港地区本部',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '星港地区东港分区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '星港地区东港分区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '星港地区苏安分区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '星港地区苏安分区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '斜塘地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '斜塘地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '东延路实验地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '东延路实验地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '独墅湖地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '独墅湖地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '景城地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '星洋地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '文萃小地区',
      legendType: '供应商1光纤线路40G',
      ...供应商1光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '星洲小地区',
      legendType: '供应商2光纤线路40G',
      ...供应商2光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '西交大附属初中',
      legendType: '供应商2光纤线路40G',
      ...供应商2光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '星湾地区',
      legendType: '供应商2光纤线路40G',
      ...供应商2光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '新城花园小地区',
      legendType: '供应商2光纤线路40G',
      ...供应商2光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '方洲小地区',
      legendType: '供应商2光纤线路40G',
      ...供应商2光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '西交大附属初中',
      legendType: '供应商2光纤线路40G',
      ...供应商2光纤线路40G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '金鸡湖地区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '青剑湖地区',
      legendType: '供应商2光纤线路40G',
      ...供应商2光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '莲花地区',
      legendType: '供应商2光纤线路40G',
      ...供应商2光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '车坊小地区',
      legendType: '供应商2光纤线路40G',
      ...供应商2光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '景城地区',
      legendType: '供应商2光纤线路40G',
      ...供应商2光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '星洋地区',
      legendType: '供应商2光纤线路40G',
      ...供应商2光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '文萃小地区',
      legendType: '供应商2光纤线路40G',
      ...供应商2光纤线路40G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '星海小地区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '星海中地区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '星海中地区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '园区一中',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '园区一中',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '胜浦实验中地区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '胜浦实验中地区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '胜浦实验小地区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '胜浦实验小地区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '翰林小地区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '翰林小地区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '西交大附属高中',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '西交大附属高中',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '翰林小地区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '翰林小地区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '教师发展中区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '教师发展中区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '娄葑地区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '娄葑地区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '唯亭实验小地区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '唯亭实验小地区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '娄葑实验小地区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '娄葑实验小地区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '跨塘实验小地区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '跨塘实验小地区',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC1大数据管理中心',
      target: '园区二实小',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: 'DC2大数据管理中心',
      target: '园区二实小',
      legendType: '供应商3光纤线路10G',
      ...供应商3光纤线路10G,
    },
    {
      source: '白榆路机房',
      target: '新城花园建筑物',
      legendType: '供应商1光纤线路10G',
      ...供应商1光纤线路10G,
    },
    {
      source: '白榆路机房',
      target: '新加花园建筑物',
      legendType: '供应商1光纤线路10G',
      ...供应商1光纤线路10G,
    },
    {
      source: '白榆路机房',
      target: '新馨花园建筑物',
      legendType: '供应商1光纤线路10G',
      ...供应商1光纤线路10G,
    },
    {
      source: '白榆路机房',
      target: '天域建筑物',
      legendType: '供应商1光纤线路10G',
      ...供应商1光纤线路10G,
    },
    {
      source: '学生公寓B区机房',
      target: '华林建筑物',
      legendType: '供应商1光纤线路10G',
      ...供应商1光纤线路10G,
    },
    {
      source: '学生公寓B区机房',
      target: '翰林建筑物',
      legendType: '供应商1光纤线路10G',
      ...供应商1光纤线路10G,
    },
    {
      source: '星华街机房',
      target: '景城建筑物',
      legendType: '供应商1光纤线路10G',
      ...供应商1光纤线路10G,
    },
    {
      source: '星华街机房',
      target: '新洲建筑物',
      legendType: '供应商1光纤线路10G',
      ...供应商1光纤线路10G,
    },
    {
      source: '星华街机房',
      target: '尚城建筑物',
      legendType: '供应商1光纤线路10G',
      ...供应商1光纤线路10G,
    },
    {
      source: '星华街机房',
      target: '星慧建筑物',
      legendType: '供应商1光纤线路10G',
      ...供应商1光纤线路10G,
    },
    {
      source: '星华街机房',
      target: '钟园建筑物',
      legendType: '供应商1光纤线路10G',
      ...供应商1光纤线路10G,
    },
    {
      source: '唯亭大道机房',
      target: '翡翠建筑物',
      legendType: '供应商1光纤线路10G',
      ...供应商1光纤线路10G,
    },
  ],
}
